# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1so19hmzoib5ipUb1gOVNze0EdTON8NGB
"""

#Importamos librerias
import cv2 # OpenCV: lectura/transformación de imágenes, contornos, etc.
import random #ayuda a poder usar funciones para generar numeros random y asi elegir imagenes aleatorias
import numpy as np # NumPy: arrays y tipos (uint8) para máscaras/umbrales
import matplotlib.pyplot as plt # Sirve para poder mostrar imágenes y títulos

imagenes = ['p1.jpg','p2.jpg','p3.jpg','p4.jpg','p5.jpg','p6.jpg']
nombre = ["Carlos","Rodrigo"]
contador = 0
puntaje_chuza = 0
# marcador por jugador
puntajes = [0, 0]
puntajes_finales = [0, 0]
calculo1 = [0,0,0,0,0]
calculo2 = [0,0,0,0,0]
# Ciclo for para los 3 rounds
for nom in range(2):
  for i in range(3):
    #carga imagen
    num = random.randint(0,5)
    img = cv2.imread(imagenes[num])

    # Convertimos en RGB
    img_RGB = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    img_gausian = cv2.GaussianBlur(img_gray, (15,15),0)

    # Parametros Blanco
    lower_blanco = np.array([250, 250, 250], dtype = np.uint8)
    upper_blanco = np.array([255, 255, 255], dtype = np.uint8)
    # Mascara y su aplicacion
    img_b = cv2.cvtColor(img_gausian,cv2.COLOR_GRAY2RGB)
    mask = cv2.inRange(img_b, lower_blanco, upper_blanco)
    result = cv2.bitwise_and(img_b,img_b, mask = mask)

    # Buscamos los contornos para contarlos
    canny = cv2.Canny(img_b,100,200)
    (contornos,_) = cv2.findContours(canny.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Mostramos lo que conto
    objetos = len(contornos)
    puntaje = abs(objetos - 10)
    if (nom == 0):
      calculo1[i] = puntaje
    if (nom == 1):
      calculo2[i] = puntaje
    puntajes[nom] = puntaje + puntajes[nom]

    contador = contador + 1

    # Graficar
    plt.figure(figsize = (15,5))
    plt.title(f"Ronda {contador} - {nombre[nom]} | Pinos: {objetos} | Puntaje ronda: {puntaje}")
    plt.imshow(img_RGB, cmap = "gray")
    plt.axis("off")

#calcular los puntajes finales  de jjugador 1
for j in range(3):
  if (calculo1[j] == 10):
    puntaje_chuza = calculo1[j+1] + calculo1[j+2]
  puntajes_finales[0] += calculo1[j] + puntaje_chuza
  puntaje_chuza = 0
print(f"Puntaje total Carlos:  {puntajes_finales[0]}")
#calcular los puntajes finales de jugador 2
for j in range(3):
  if (calculo2[j] == 10):
    puntaje_chuza = calculo2[j+1] + calculo2[j+2]
  puntajes_finales[1] += calculo2[j] + puntaje_chuza
  puntaje_chuza = 0
print(f"Puntaje total Rodrigo: {puntajes_finales[1]}")

!sudo apt install tesseract-ocr
!pip install pytesseract